---
title: "RWorksheet_Delatina#2"
author: "Angel"
date: "2024-09-21"
output:
  html_document: default
  pdf_document: default
---

#1A
```{r}
vector_a <- -5:5
print(vector_a)
```
#1B
```{r}
x <- 1:7
print(x)
```
#2
```{r}
vector_b <- seq(1, 3, by=0.2)
print(vector_b)
```

#3A
```{r}
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
          34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 
          51, 35, 24, 33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 
          19, 30, 61, 54, 58, 26, 18)
third_element <- ages[3]
third_element
```
#3B
```{r}
second_and_fourth <- ages[c(2, 4)]
second_and_fourth
```

#3C
```{r}
excluded_elements <- ages[-c(4, 12)]
excluded_elements
```

#4A
```{r}
x <- c("first"=3, "second"=0, "third"=9)
names(x)
accessed_values <- x[c("first", "third")]
accessed_values
```
#5A
```{r}
x <- -3:2
x[2] <- 0
x
```

#6A
```{r}
months <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

fuel_data <- data.frame(months, price_per_liter, purchase_quantity)
fuel_data
```

#6B
```{r}
expenditure <- price_per_liter * purchase_quantity
average_expenditure <- mean(expenditure)
average_expenditure
```

#7A
```{r}
data <- c (length(rivers),sum(rivers),mean(rivers),median(rivers),var(rivers),sd(rivers),min(rivers),max(rivers))
```
#8A
```{r}
celebrity_names <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods",
                     "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos",
                     "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali",
                     "Paul McCartney", "George Lucas", "Elton John", "David Letterman",
                     "Phil Mickelson", "J.K Rowling", "Brad Pitt", "Peter Jackson",
                     "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")

power_ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)

pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 19, 25, 25, 45, 32, 40, 31)

```
#8B
```{r}
rowling_index <- which(celebrity_names == "J.K. Rowling") 
power_ranking[rowling_index] <- 15 
pay[rowling_index] <- 90 

print(power_ranking)
print(pay)
```
#8C
```{r}
write.csv(data.frame(celebrity_names, power_ranking, pay), "PowerRanking.csv")

power_data <- read.csv("PowerRanking.csv")
power_data

```
#8D
```{r}
celebrity_data <- data.frame(PowerRanking = power_ranking, Name = celebrity_names, Pay = pay)

ranks_subset <- celebrity_data[10:20,]
save(ranks_subset, file = "Ranks.RData")
print(ranks_subset)
```
#9A
```{r}
options(repos = c(CRAN = "https://cloud.r-project.org/"))
install.packages("readxl")
library(readxl)
hotels_data <- read_excel("C:/Documents/RBasics/CS101_Data-Science/Worksheet2/hotels-vienna.xlsx")
hotels_data
```
#9B
```{r}
dim(hotels_data)

```
#9C
```{r}
selected_data <- hotels_data
  select<- c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")
```
#9D
```{r}
save(selected_data, file = "new.RData")
load("new.RData")
```
#9E

```{r}
head(selected_data)
tail(selected_data)
```
#10A
```{r}
vegetables <- c("Potato", "Cucumber", "Carrot", "Lettuce", "Eggplant", "Cabbage", "Peas", "Squash", "Broccoli", "Radish")
print(vegetables)
```
#10B
```{r}
vegetables <- c(vegetables, "Cauliflower", "Peppers")
print(vegetables)
```
#10C
```{r}
vegetables <- append(vegetables, c("Leek", "Kale", "Celery", "Chives"), after = 5)
print(vegetables)

length_of_list <- length(vegetables)
print(length_of_list)
```
#10D

```{r}
vegetables <- vegetables[-c(5, 10, 15)]
remaining_vegetables <- length(vegetables)
print(vegetables)
print(remaining_vegetables)
```

