---
title: "RWorksheet_Delatina#3B"
author: "Angel"
date: "2024-10-03"
output: pdf_document
---

#1A
```{r}
data <- data.frame(
  Respondents = 1:20,
  Sex = c(2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2),
  Fathers_Occupation = c(1, 3, 2, 2, 1, 1, 2, 3, 1, 1, 1, 2, 3, 2, 1, 2, 3, 1, 1, 2),
  Persons_at_Home = c(5, 7, 3, 8, 5, 3, 6, 8, 7, 4, 9, 5, 7, 3, 8, 8, 9, 11, 7, 6),
  Siblings_at_School = c(6, 4, 3, 1, 2, 3, 5, 1, 4, 2, 2, 5, 5, 7, 1, 1, 2, 3, 2, 3),
  Types_of_Houses = c(1, 2, 3, 1, 1, 3, 3, 2, 1, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 2)
)
data
```
#1B
```{r}
str(data)
```
#1C
```{r}
mean_siblings <- mean(data$Siblings_at_School)
mean_siblings
```
#1D
```{r}
subset_rows_1_2<- data[1:2,]
subset_rows_1_2
```
#1E
```{r}
subset_3_5_rows_2_4_col <- data[c(3,5),c(2,4)]
subset_3_5_rows_2_4_col
```
#1F
```{r}
types_houses <- data$Types_of_Houses
types_houses
```
#1G
```{r}
male_farmers <- data[data$Sex == 1 & data$Fathers_Occupation == 1, ]
male_farmers

```
#1H
```{r}
female_siblings_5_or_more <- data[data$Sex == 2 & data$Siblings_at_School>=5,]
female_siblings_5_or_more
```
#2
```{r}
df = data.frame(Ints=integer(),
Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))

```
#3A
```{r}
household_data <- read.csv("C:/Users/HP/OneDrive/文档/Data Science/CS101/Worksheet3/HouseholdData.csv")
household_data
```
#3B
```{r}
household_data$Sex <- factor(household_data$Sex, levels = c("Male","Female"))
household_data$Sex <-as.integer(household_data$Sex)
household_data
```
#3C
```{r}
str(household_data) 
head(household_data)

unique(household_data$Types_of_Houses)
 
 if("Types_of_Houses"%in% names(household_data)){
   household_data$Types_of_Houses<- factor(household_data$Types_of_Houses,
                                            levels = c("Wood", "Concrete", "Semi-Concret"),                                             labels= c(1, 2, 3))
   household_data$Types_of_Houses <- as.integer(household_data$Types_of_Houses)
   
   print(head(household_data))
}else{
   print("The column 'Types_of_Houses' does not exist in the data frame.")
}
```
#3D
```{r}
str(household_data)
head(household_data)
names(household_data)[names(household_data) == "Fathers Occupation"]<- "Fathers-Occupation"
names(household_data)

  if("Fathers_Occupation" %in% names(household_data)){
    household_data$Fathers_Occupation <- factor(household_data$Fathers_Occupation,
                                              levels= c("Farmer", "Driver", "Others"),
                                              labels= c (1, 2, 3 ))
    household_data$Fathers-Occupation <- as.integer(household_data$Fathers_Occupation)
    print(head(household_data))
} else{
    print("The column 'Fathers_Occupation' still does not exist in the data frame")
}
```
#3E
```{r}
str(household_data)
names(household_data)
head(household_data)
females_with_driver_father <- subset(household_data, Sex == "Female"& 'Fathers_Occupation' == "Driver")
```
#3F
```{r}
str(household_data)
names(household_data)

respondents_with_5_siblings <- subset(household_data, Siblings.at.School >= 5)
respondents_with_5_siblings
```